# Generated by Django 5.2.5 on 2025-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NightWorkerInsight",
            fields=[
                ("insight_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=512)),
                ("published_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "night_worker_insights",
                "ordering": ["-published_date", "-insight_id"],
                "managed": False,
            },
        ),
    ]
