# Generated by Django 5.2.5 on 2025-09-17 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlowWithIt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueCBD",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("osm_id", models.BigIntegerField()),
                (
                    "osm_type",
                    models.CharField(
                        choices=[
                            ("node", "node"),
                            ("way", "way"),
                            ("relation", "relation"),
                        ],
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("venue_type", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "opening_hours_raw",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mon", models.CharField(blank=True, max_length=64, null=True)),
                ("tue", models.CharField(blank=True, max_length=64, null=True)),
                ("wed", models.CharField(blank=True, max_length=64, null=True)),
                ("thu", models.CharField(blank=True, max_length=64, null=True)),
                ("fri", models.CharField(blank=True, max_length=64, null=True)),
                ("sat", models.CharField(blank=True, max_length=64, null=True)),
                ("sun", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "venue_cbd",
                "indexes": [
                    models.Index(fields=["name"], name="idx_venue_cbd_name"),
                    models.Index(fields=["venue_type"], name="idx_venue_cbd_type"),
                    models.Index(
                        fields=["latitude", "longitude"], name="idx_venue_cbd_latlon"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("osm_type", "osm_id"),
                        name="uniq_venue_cbd_osmtype_osmid",
                    )
                ],
            },
        ),
    ]
