# Generated by Django 5.2.5 on 2025-10-08 23:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlowWithIt", "0002_venuecbd"),
    ]

    operations = [
        migrations.CreateModel(
            name="HazardReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("kind", models.CharField(blank=True, max_length=32)),
                ("note_short", models.CharField(blank=True, max_length=140)),
                ("severity", models.PositiveSmallIntegerField(default=1)),
                ("ttl_secs", models.PositiveIntegerField(default=1800)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("fp", models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="GlowWithIt__expires_a22a69_idx"
                    ),
                    models.Index(
                        fields=["lat", "lng"], name="GlowWithIt__lat_34bf0b_idx"
                    ),
                ],
            },
        ),
    ]
