# Generated by Django 5.2.5 on 2025-10-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GlowWithIt", "0002_venuecbd"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoLine",
            fields=[
                ("geo_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("geom", models.BinaryField()),
            ],
            options={
                "db_table": "geo_lines",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GeoPoint",
            fields=[
                ("geo_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("geom", models.BinaryField()),
            ],
            options={
                "db_table": "geo_points",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LightingLamp",
            fields=[
                ("osm_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("tags", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(blank=True, default="overpass", max_length=32),
                ),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "lighting_lamps",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LightingLitway",
            fields=[
                ("osm_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("tags", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(blank=True, default="overpass", max_length=32),
                ),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "lighting_litways",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VenueCBDStage",
            fields=[
                ("osm_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("osm_type", models.CharField(blank=True, max_length=16, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("venue_type", models.CharField(blank=True, max_length=64, null=True)),
                ("address", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "opening_hours_raw",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("mon", models.CharField(blank=True, max_length=32, null=True)),
                ("tue", models.CharField(blank=True, max_length=32, null=True)),
                ("wed", models.CharField(blank=True, max_length=32, null=True)),
                ("thu", models.CharField(blank=True, max_length=32, null=True)),
                ("fri", models.CharField(blank=True, max_length=32, null=True)),
                ("sat", models.CharField(blank=True, max_length=32, null=True)),
                ("sun", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "db_table": "venues_cbd",
                "managed": False,
            },
        ),
    ]
